const { v4: uuidv4 } = require('uuid')
//let items = require('../items.js')
const { pool } = require("../../config/db")
const fastify = require('fastify')()
fastify
  .register(require('fastify-stripe'), {
    apiKey: 'sk_test_51L415IJiREfmU884qVpd0lkOp8anxRFCQXbAZ53LJdLLlO3PDZoiZKisWa0hFkblFzwnO1IoSUqvRIEnVtlW1heh00Fd6oXttN',
    name: 'test',
    timeout: 24000 // in ms (this is 24 seconds)
  })
const { stripe } = fastify


const stripePayment = async (req, reply) => {
    const { email,product , authToken } = req.body;
    const { token } = authToken;
    const { card } = token;

    console.log(card);


  
    console.log("============================================== payment initiate =======================")

 
 
    // unique ID generated by client
     const idempotencyKey = uuidv4()





     try {
      
         
   
        const session = await stripe.checkout.sessions.create({
            line_items: [{
              name: 'Kavholm rental',
              amount: 1000,
              currency: 'gbp',
              quantity: 1,
            }],
            payment_intent_data: {
              application_fee_amount: 123,
             
            },
            mode: 'payment',
            
          });
          

         console.log("charge response")
         console.log(session)
           
         
      
         res.json(session)
         
     } catch (err) {
         console.log("=========================================== error ==========================")
        console.log(err)
        res.json(err)
     }

}


module.exports = {
    stripePayment
}